### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by gn-ahmad** [drov0/steemsnippets#3]
Hello dear friend,
After examining your project, I become eager to accompany you in it. I wanted to ask you if it is possible to design your project's Logo to have the smallest action in your great and awsemne project.
I hope you let me, I'm eagerly waiting for your answer in order to take a small part of your activities.

**Comment by drov0** [comment]
Sure !

**Comment by gn-ahmad** [comment]
Hi dear friend,
please check this
each one you like, i will send pull request for that.
![logo02](https://user-images.githubusercontent.com/35422774/39960223-32c57636-5634-11e8-98a7-e156a4553340.jpg)
![logo01](https://user-images.githubusercontent.com/35422774/39960224-32f56d0a-5634-11e8-8b24-ee02a7840c2b.jpg)

**Comment by drov0** [comment]
Hey ! 

I love the first one :+1: 

https://user-images.githubusercontent.com/35422774/39960223-32c57636-5634-11e8-98a7-e156a4553340.jpg

Can you add an "S" at the end ? 

Then please submit a pull request :)

**Comment by gn-ahmad** [comment]
Hey, thank you
all right.

**Comment by anilkilic** [comment]
Hey Martin,

Just to let you know that there is a similar looking logo in here, https://play.google.com/store/apps/details?id=xyz.klinker.messenger

**Comment by gn-ahmad** [comment]
@drov0
Hello dear friend, I beg my pardon because I guess that accidently the Lego which I have designed has a similar one. Is it possible to replace a new Lego with some changes in the project in order to prevent misunderstanding?

**Comment by drov0** [comment]
@gn-ahmad that would be ideal

**Comment by gn-ahmad** [comment]
@drov0 I hope you like! 
![logoas](https://user-images.githubusercontent.com/35422774/40071199-5c16639e-5885-11e8-8e84-694448a7f2ba.png)

![logoasss](https://user-images.githubusercontent.com/35422774/40071634-9865e4ae-5886-11e8-95ff-5c383c748c1e.png)

**Comment by drov0** [comment]
I like the first one best. Thanks for your efforts, No need to submit a pull request, after some thoughts I figured it wouldn't be best to put images in a git repo as it drastically incrases the size of it. I'll add it on the readme mentioning you.
