### ISSUE TITLE
Licenses in packages differ from the main project

### ISSUE THREAD

**Issue by tdreid** [drov0/steemsnippets#4]
This isn't necessarily bad because the licenses may be compatible.  But since the main project switched to MIT license and there are a few different licenses, mainly GNU, listed in package.json for various snippets it is probably simplest to use MIT license everywhere within the project. 

l opened a PR with the proposed license updates, @drov0.

**Comment by drov0** [comment]
Aah yeah I forgot to change all the licenses when I changed the license. merged the PR, thanks a lot :)
