### ISSUE TITLE
Proposal For Copy Writing

### ISSUE THREAD

**Issue by ewuoso** [drov0/steemsnippets#6]
i will like to write faq, about us, contact us and privacy policy for you.

**Comment by drov0** [comment]
Hello, 

Thanks for proposing, but I guess there isn't really a need for it, the project is self explanatory, there is no need for a privacy policy, an about us is like my steem blog which is linked, same goes for contact us.

**Comment by ewuoso** [comment]
What about faq

**Comment by drov0** [comment]
No real need as well, I've already addressed most of the questions in the readme.

**Comment by ewuoso** [comment]
Have fun
